### ISSUE TITLE
Also launches external Mail app on MacOS

### ISSUE THREAD

**Issue by waddles** [jonroig/MailtOWA#1]
With Chrome 79.0.3945.88 on MacOS Catalina 10.15.2, the extension correctly opens links in OWA but it does not cancel the default behaviour so I get 2 compose windows:
   1. Chrome tab with OWA
   1. MacOS Mail app

Both windows have the same content.

I only installed the extension today so haven't checked any other versions.

Looks like the call to `e.preventDefault()` is not working.

**Comment by jonroig** [comment]
Oh... interesting. I don't have Catalina on my machine yet...  will try and take a look in the next day or two.

**Comment by jonroig** [comment]
I finally upgraded and it seems ok? Have this fixed itself for you?

**Comment by jonroig** [comment]
Uhhh... took me awhile, but I fixed this. Submitted the latest version (1.1) to the Google Chrome Store which should fix the problem...
