### ISSUE TITLE
The extension does not work from some websites

### ISSUE THREAD

**Issue by raphaelp-github** [jonroig/MailtOWA#5]
The extension does not work from some websites, mailto redirects to a third party messaging application. Works well since your Github test. 

https://user-images.githubusercontent.com/34160362/108524486-5d0f1b80-72cf-11eb-93bc-d4a7b7f08984.mp4

**Comment by jonroig** [comment]
It pretty much just intercepts mailto: links... it'd be helpful to design a simple test case to see how easy it is to route around it...
