### ISSUE TITLE
Have you considered a custom protocol handler instead?

### ISSUE THREAD

**Issue by dellagustin-sap** [jonroig/MailtOWA#6]
Hello, thanks for this extension.

Have you considered using a custom protocol handler instead of injecting a script on every page?
Would it be a feasible option?
https://developers.google.com/web/updates/2011/06/Registering-a-custom-protocol-handler

**Comment by jonroig** [comment]
That's.... a fair question. (Apologies for the delayed response.) It's been so long that I had to look this up and figure out why I did it this way...

In this case, it's something MS would have to do:
"The URL template supplied when registering must be of the same domain as the webpage attempting to perform the registration or the registration will fail. For example, http://example.com/homepage.html can register a protocol handler for http://example.com/handle_mailto/%s, but not for http://example.org/handle_mailto/%s."

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers
